//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnchorTest.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Ch1Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Ch1Settings defaultInstance = ((Ch1Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Ch1Settings())));

        public static Ch1Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlipVertical
        {
            get
            {
                return ((bool)(this["FlipVertical"]));
            }
            set
            {
                this["FlipVertical"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlipHorizontal
        {
            get
            {
                return ((bool)(this["FlipHorizontal"]));
            }
            set
            {
                this["FlipHorizontal"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RotateClockStep
        {
            get
            {
                return ((int)(this["RotateClockStep"]));
            }
            set
            {
                this["RotateClockStep"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Brightness
        {
            get
            {
                return ((int)(this["Brightness"]));
            }
            set
            {
                this["Brightness"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Contrast
        {
            get
            {
                return ((int)(this["Contrast"]));
            }
            set
            {
                this["Contrast"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Red
        {
            get
            {
                return ((int)(this["Red"]));
            }
            set
            {
                this["Red"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Green
        {
            get
            {
                return ((int)(this["Green"]));
            }
            set
            {
                this["Green"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Blue
        {
            get
            {
                return ((int)(this["Blue"]));
            }
            set
            {
                this["Blue"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CameraIndex
        {
            get
            {
                return ((int)(this["CameraIndex"]));
            }
            set
            {
                this["CameraIndex"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CameraName
        {
            get
            {
                return ((string)(this["CameraName"]));
            }
            set
            {
                this["CameraName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CameraId
        {
            get
            {
                return ((string)(this["CameraId"]));
            }
            set
            {
                this["CameraId"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SnapshotPath
        {
            get
            {
                return ((string)(this["SnapshotPath"]));
            }
            set
            {
                this["SnapshotPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ZoomFactor
        {
            get
            {
                return ((int)(this["ZoomFactor"]));
            }
            set
            {
                this["ZoomFactor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ZoomCenterOnSettingsAreaX
        {
            get
            {
                return ((int)(this["ZoomCenterOnSettingsAreaX"]));
            }
            set
            {
                this["ZoomCenterOnSettingsAreaX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ZoomCenterOnSettingsAreaY
        {
            get
            {
                return ((int)(this["ZoomCenterOnSettingsAreaY"]));
            }
            set
            {
                this["ZoomCenterOnSettingsAreaY"] = value;
            }
        }
    }
}
